### ISSUE TITLE
Improve matcher and directory names

### ISSUE THREAD

**Issue by jekuno** [rprt/rspec-page-regression#9]
Follwing clean code coventions it would make sense to replace the `expectation` directory by a more descriptive name such as `reference_screenshots` (btw: note that the directory name should be pluralized similar to the directories 'features', 'factories' and 'models').

Accordingly I would suggest to introduce a more descriptive matcher name i.e. change it from `expect(page).to match_expectation` to `expect(page).to match_reference_screenshot`.

**Comment by ronen** [comment]
Yes you're right that would be much better.

This could be introduced via a deprecation: if `match_expectation` is used it should warn about the the deprecation and look for the reference images in `expectation/`, otherwise `match_reference_screenshot` would look in `reference_images`.    (And actually, this directory and the tmp directory should be configurable anyway via `RSpec::PageRegression.configure`)

and as long as the API is improving,  `match_reference_screenshot` should take a keyword argument such as `path:` to override the reference image, rather than a positional argument.  That'd mesh better with other options such as suggested in #4, #7, and #11 

And also in the README, "expectation" and "expectation image" should be replaced with "reference image".

Unfortunately I don't have time to do this right now, but I'm happy to accept a PR!

**Comment by jekuno** [comment]
Right now working on this one for #17
